### ISSUE TITLE
urweb via homebrew will not build the demo

### ISSUE THREAD

**Issue by ammkrn** [urweb/urweb#243]
The instructions for building the demo given at http://www.impredicative.com/ur/demo/ do not succeed after installing via homebrew.

The Ur/Web compiler, version 20200209
MacOS version 11.4

Running the command `urweb -dbms sqlite -db /path_to_db.sqlite -demo /Demo -noEmacs demo` produces the following output, and no executable:
```
$ urweb -dbms sqlite -db /path_to_db.sqlite -demo /Demo -noEmacs demo
/Users/my_machine/urweb/demo/crud.urs:2:18: (to 2:24) syntax error: deleting  NAME COLON
/Users/my_machine/urweb/demo/crud.urs:2:25: (to 2:32) syntax error: deleting  SYMBOL COMMA
/Users/my_machine/urweb/demo/crud.ur:2:18: (to 2:24) syntax error: deleting  NAME COLON
/Users/my_machine/urweb/demo/crud.ur:2:25: (to 2:32) syntax error: deleting  SYMBOL COMMA
/Users/my_machine/urweb/demo/crud.ur:12:5: (to 12:9) syntax error: replacing  NAME with  RBRACE
/Users/my_machine/urweb/demo/crud.ur:12:12: (to 12:12) syntax error: inserting  LPAREN
/Users/my_machine/urweb/demo/crud.ur:16:35: (to 16:64) This is an expression but not a pattern.
/Users/my_machine/urweb/demo/crud.ur:18:15: (to 18:16) syntax error: replacing  RBRACE with  RPAREN
/Users/my_machine/urweb/demo/crud.ur:22:0: (to 22:20) Additional arguments not allowed after pattern
/Users/my_machine/urweb/demo/crud.ur:21:0: (to 21:19) Additional arguments not allowed after pattern
/Users/my_machine/urweb/demo/crud.ur:24:9: (to 24:13) Invalid FFI mode
/Users/my_machine/urweb/demo/crud.ur:24:17: (to 24:21) syntax error: replacing  NAME with  RBRACE
/Users/my_machine/urweb/demo/crud.ur:22:0: (to 22:20) Additional arguments not allowed after pattern
/Users/my_machine/urweb/demo/crud.ur:21:0: (to 21:19) Additional arguments not allowed after pattern
/Users/my_machine/urweb/demo/crud.ur:24:9: (to 24:13) Invalid FFI mode
/Users/my_machine/urweb/demo/crud.ur:24:24: (to 24:24) syntax error: inserting  LPAREN
/Users/my_machine/urweb/demo/crud.ur:28:47: (to 28:74) This is an expression but not a pattern.
/Users/my_machine/urweb/demo/crud.ur:30:27: (to 30:28) syntax error: replacing  RBRACE with  RPAREN
/Users/my_machine/urweb/demo/crud.ur:70:32: (to 70:37) syntax error: deleting  DOT NAME
/Users/my_machine/urweb/demo/crud.ur:82:31: (to 82:36) syntax error: deleting  DOT NAME
/Users/my_machine/urweb/demo/crud.ur:134:39: (to 134:44) syntax error: deleting  DOT NAME
/Users/my_machine/urweb/demo/crud2.ur:1:15: (to 1:23) syntax error: deleting  COMMA NAME COLON
/Users/my_machine/urweb/demo/crud2.ur:7:19: (to 7:47) Additional arguments not allowed after pattern
/Users/my_machine/urweb/demo/crud2.ur:5:19: (to 5:30) Additional arguments not allowed after pattern
/Users/my_machine/urweb/demo/crud2.ur:9:31: (to 9:35) syntax error: replacing  NAME with  RBRACE
/Users/my_machine/urweb/demo/crud2.ur:9:38: (to 9:49) Badly capitalized constructor name in pattern
/Users/my_machine/urweb/demo/crud2.ur:7:19: (to 7:47) Additional arguments not allowed after pattern
/Users/my_machine/urweb/demo/crud2.ur:9:38: (to 9:38) syntax error: inserting  LPAREN
/Users/my_machine/urweb/demo/crud2.ur:9:38: (to 9:49) Badly capitalized constructor name in pattern
/Users/my_machine/urweb/demo/crud2.ur:10:37: (to 10:44) syntax error: deleting  EQ LBRACE NAME
/Users/my_machine/urweb/demo/crud2.ur:27:48: (to 31:102) This is an expression but not a pattern.
/Users/my_machine/urweb/demo/crud2.ur:33:39: (to 35:18) syntax error: deleting  RBRACE RBRACE END
/Users/my_machine/urweb/demo/crud2.ur:27:48: (to 31:102) This is an expression but not a pattern.
/Users/my_machine/urweb/demo/crud2.ur:36:0: (to 36:0) syntax error found at EOF
/Users/my_machine/urweb/demo/crud3.ur:7:19: (to 7:38) Additional arguments not allowed after pattern
/Users/my_machine/urweb/demo/crud3.ur:5:19: (to 5:30) Additional arguments not allowed after pattern
/Users/my_machine/urweb/demo/crud3.ur:9:39: (to 9:43) syntax error: replacing  NAME with  RBRACE
/Users/my_machine/urweb/demo/crud3.ur:23:47: (to 23:93) This is an expression but not a pattern.
/Users/my_machine/urweb/demo/crud3.ur:23:83: (to 23:86) This is an expression but not a pattern.
/Users/my_machine/urweb/demo/crud3.ur:25:38: (to 25:38) syntax error: inserting  LBRACE
Parse failure
```

I wasn't able to install from the source either. I got over the initial hurdles about openssl and ICU by grafting the setup from the travis.yml file before calling `configure`, but building still fails with something that looks like this user's issue in #239: https://github.com/urweb/urweb/issues/239#issuecomment-1002650672, though I'm using Apple clang version 12.0.0 (clang-1200.0.32.29)

```
urweb.c:3122:23: error: expected identifier or '('
  static uw_Basis_int true = 1;
                      ^
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/stdbool.h:16:14: note: expanded from macro 'true'
#define true 1
             ^
urweb.c:3123:23: error: expected identifier or '('
  static uw_Basis_int false = 0;
                      ^
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/stdbool.h:17:15: note: expanded from macro 'false'
#define false 0
              ^
urweb.c:3126:20: error: cannot take the address of an rvalue of type 'int'
    return (char *)&false;
                   ^~~~~~
urweb.c:3128:20: error: cannot take the address of an rvalue of type 'int'
    return (char *)&true;
                   ^~~~~
urweb.c:3226:24: error: expected identifier or '('
  static uw_Basis_bool true = uw_Basis_True;
                       ^
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/stdbool.h:16:14: note: expanded from macro 'true'
#define true 1
             ^
urweb.c:3227:24: error: expected identifier or '('
  static uw_Basis_bool false = uw_Basis_False;
                       ^
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/stdbool.h:17:15: note: expanded from macro 'false'
#define false 0
              ^
urweb.c:3230:12: error: cannot take the address of an rvalue of type 'int'
    return &true;
           ^~~~~
urweb.c:3232:12: error: cannot take the address of an rvalue of type 'int'
    return &false;
           ^~~~~~
8 errors generated.
make[1]: *** [urweb.lo] Error 1
make: *** [all-recursive] Error 1
```
